### ISSUE TITLE
In-App: more offers and special offer overlays

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#181]
RA: special offer layout

**Comment by Laura-O4S** [comment]
Special offer:
50 credits
5 timer boosters
2 converter boosters
remove ads

**Comment by Rich-O4S** [comment]
![levelmenu_iap-alternative_0008_buy star credits](https://cloud.githubusercontent.com/assets/11824245/17737584/9028c384-6485-11e6-871c-f28be85a13ee.jpg)

![diner-special-offers](https://cloud.githubusercontent.com/assets/11824245/17737609/af857e3e-6485-11e6-86ac-bf69c752d93f.jpg)


Ignore the values shown. I've created a special-offers scene but it is up to us whether we move scenes or try keep within the IAP scene. Would need to think about if you only see the tab if purchasing from the menu rather than in-game

**Comment by Laura-O4S** [comment]
- [] select close = show buy currency overlay when return to menu
- [] if already bought ads, replace with 2 blaster boosters

**Comment by Laura-O4S** [comment]
- [ ] select close = return to menu and show buy currency overlay
- [ ] if already removed ads = replace with 2 x laser boosters

**Comment by Laura-O4S** [comment]
check special offer panel shows in right place!
